### ISSUE TITLE
什么时候更新最新的1.9.2版本

### ISSUE THREAD

**Issue by ZWBNice** [jingliancui/XamarinFormsWechatSDKSample#1]

**Comment by jingliancui** [comment]
看找个时间更新一下

**Comment by ZWBNice** [comment]
好的 谢谢！

**Comment by ZWBNice** [comment]
大佬  能不能整个deeplink 的sdk 极光魔链 啊


| |
张文博 ios
|
|
***@***.***
|
签名由网易邮箱大师定制


在2022年01月17日 ***@***.***> 写道：

看找个时间更新一下

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jingliancui** [comment]
iOS已更新到1.9.9，不兼容xamarin.ios, 兼容.net6 ios项目
